# ILS iOS SwiftLint Configuration
included:
  - ILSApp/ILSApp

excluded:
  - ILSApp/ILSApp/build

disabled_rules:
  - trailing_whitespace
  - line_length
  - todo
  - force_unwrapping

opt_in_rules:
  - empty_count
  - closure_spacing
  - implicit_return

identifier_name:
  min_length:
    warning: 1
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id

file_length:
  warning: 500
  error: 600

type_body_length:
  warning: 450
  error: 600

function_body_length:
  warning: 50
  error: 100

cyclomatic_complexity:
  warning: 15
  error: 25

function_parameter_count:
  warning: 6
  error: 8

nesting:
  type_level: 3
  function_level: 4
