# SwiftLint Configuration for ILS iOS/macOS

included:
  - ILSApp/ILSApp
  - ILSApp/ILSMacApp
  - Sources

excluded:
  - ILSApp/ILSApp.xcodeproj
  - .build
  - DerivedData
  - Package.swift

line_length:
  warning: 200
  error: 300
  ignores_comments: true

type_body_length:
  warning: 400
  error: 800

file_length:
  warning: 600
  error: 1000

function_body_length:
  warning: 80
  error: 150

disabled_rules:
  - trailing_whitespace
  - todo
  - opening_brace
  - identifier_name
  - type_name
  - nesting

opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_filter_count
  - discouraged_optional_boolean
  - empty_string
  - first_where
  - last_where
  - modifier_order
  - redundant_nil_coalescing
  - sorted_first_last

force_cast: warning
force_try: warning
