name: ILSApp
fileGroups:
  - ILSApp.xctestplan

options:
  bundleIdPrefix: com.ils
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  generateEmptyDirectories: false

packages:
  ILSShared:
    path: ..
  MarkdownUI:
    url: https://github.com/gonzalezreal/swift-markdown-ui
    from: "2.4.0"
  HighlightSwift:
    url: https://github.com/appstefan/HighlightSwift
    from: "1.0.0"

targets:
  # ──────────────────────────────────────────────
  # iOS App
  # ──────────────────────────────────────────────
  ILSApp:
    type: application
    platform: iOS
    sources:
      - path: ILSApp
        excludes:
          - "**/*.md"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ils.app
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.0"
        DEVELOPMENT_TEAM: HC36V7B67Z
        INFOPLIST_FILE: ILSApp/Info.plist
        CODE_SIGN_ENTITLEMENTS: ILSApp/ILSApp.entitlements
        GENERATE_INFOPLIST_FILE: "YES"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_EMIT_LOC_STRINGS: "YES"
        ENABLE_PREVIEWS: "YES"
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
    dependencies:
      - package: ILSShared
        product: ILSShared
      - package: MarkdownUI
        product: MarkdownUI
      - package: HighlightSwift
        product: HighlightSwift
    info:
      path: ILSApp/Info.plist
      properties:
        NSAppTransportSecurity:
          NSAllowsLocalNetworking: true
        CFBundleURLTypes:
          - CFBundleURLName: com.ils.app
            CFBundleURLSchemes:
              - ils
        NSFaceIDUsageDescription: "Face ID is used to protect your server credentials stored in the Keychain."
    entitlements:
      path: ILSApp/ILSApp.entitlements

  # ──────────────────────────────────────────────
  # macOS App
  # ──────────────────────────────────────────────
  # ──────────────────────────────────────────────
  # UI Tests
  # ──────────────────────────────────────────────
  ILSAppUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: ILSAppUITests
        excludes:
          - "**/*.md"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ils.app.uitests
        SWIFT_VERSION: "5.0"
        DEVELOPMENT_TEAM: HC36V7B67Z
        GENERATE_INFOPLIST_FILE: "YES"
        TEST_HOST: ""
        TEST_TARGET_NAME: ILSApp
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
    dependencies:
      - target: ILSApp

  # ──────────────────────────────────────────────
  # macOS App
  # ──────────────────────────────────────────────
  ILSMacApp:
    type: application
    platform: macOS
    sources:
      # macOS-specific code (entry point, AppDelegate, WindowManager, macOS views)
      - path: ILSMacApp
        excludes:
          - "**/*.md"
      # Shared cross-platform code from iOS app directory
      # (ViewModels, Services, Models, Utils, Theme, Views — all use SwiftUI/Foundation)
      - path: ILSApp
        excludes:
          - ILSAppApp.swift
          - Assets.xcassets
          - Info.plist
          - ILSApp.entitlements
          - PrivacyInfo.xcprivacy
          - "**/*.md"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ils.mac
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.0"
        DEVELOPMENT_TEAM: HC36V7B67Z
        INFOPLIST_FILE: ILSMacApp/Info.plist
        CODE_SIGN_ENTITLEMENTS: ILSMacApp/ILSMacApp.entitlements
        GENERATE_INFOPLIST_FILE: "YES"
        ENABLE_HARDENED_RUNTIME: "YES"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_EMIT_LOC_STRINGS: "YES"
        ENABLE_PREVIEWS: "YES"
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
    dependencies:
      - package: ILSShared
        product: ILSShared
      - package: MarkdownUI
        product: MarkdownUI
      - package: HighlightSwift
        product: HighlightSwift
    info:
      path: ILSMacApp/Info.plist
      properties:
        NSAppTransportSecurity:
          NSAllowsLocalNetworking: true
        CFBundleURLTypes:
          - CFBundleURLName: com.ils.mac
            CFBundleURLSchemes:
              - ils
    entitlements:
      path: ILSMacApp/ILSMacApp.entitlements

# ──────────────────────────────────────────────
# Schemes
# ──────────────────────────────────────────────
schemes:
  ILSApp:
    build:
      targets:
        ILSApp: all
        ILSAppUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - name: ILSAppUITests

  ILSMacApp:
    build:
      targets:
        ILSMacApp: all
    run:
      config: Debug

  ILSApp-WithBackend:
    build:
      targets:
        ILSApp: all
      preActions:
        - script: |
            # Start backend if not already running
            if ! lsof -i :9999 -sTCP:LISTEN -P -n > /dev/null 2>&1; then
              cd "${WORKSPACE_PATH}/.."
              PORT=9999 swift run ILSBackend > /tmp/ils-backend.log 2>&1 &
              echo $! > /tmp/ils-backend.pid
              # Wait for backend health
              for i in $(seq 1 30); do
                curl -sf http://localhost:9999/api/v1/sessions?page=1\&per=1 > /dev/null 2>&1 && break
                sleep 1
              done
            fi
          name: Start Backend
          settingsTarget: ILSApp
    run:
      config: Debug
      postActions:
        - script: |
            [ -f /tmp/ils-backend.pid ] && kill $(cat /tmp/ils-backend.pid) 2>/dev/null
            rm -f /tmp/ils-backend.pid
          name: Stop Backend

  ILSMacApp-WithBackend:
    build:
      targets:
        ILSMacApp: all
      preActions:
        - script: |
            # Start backend if not already running
            if ! lsof -i :9999 -sTCP:LISTEN -P -n > /dev/null 2>&1; then
              cd "${WORKSPACE_PATH}/.."
              PORT=9999 swift run ILSBackend > /tmp/ils-backend.log 2>&1 &
              echo $! > /tmp/ils-backend.pid
              # Wait for backend health
              for i in $(seq 1 30); do
                curl -sf http://localhost:9999/api/v1/sessions?page=1\&per=1 > /dev/null 2>&1 && break
                sleep 1
              done
            fi
          name: Start Backend
          settingsTarget: ILSMacApp
    run:
      config: Debug
      postActions:
        - script: |
            [ -f /tmp/ils-backend.pid ] && kill $(cat /tmp/ils-backend.pid) 2>/dev/null
            rm -f /tmp/ils-backend.pid
          name: Stop Backend
