import SwiftUI

/// Detailed sheet showing a full breakdown of context window token usage.
///
/// Presents a circular arc progress indicator, per-category token breakdown rows,
/// warning banners when approaching the context limit, and a fork-session button
/// for proactive session management. Designed to be presented as a sheet with
/// medium and large detent sizes.
///
/// ## Token Categories
/// - **Cached History** — tokens read from cache (prior conversation history)
/// - **New Input** — fresh prompt content (inputTokens minus cached portions)
/// - **Tool Context** — content being newly cached (files, tool outputs)
/// - **Output** — Claude's response tokens for this turn
///
/// ## Warning Levels
/// - ≥ 80%: Yellow warning banner — "Approaching context limit"
/// - ≥ 95%: Red critical banner — "Context critically full"
///
/// ## Topics
/// ### Input Properties
/// - ``sessionId`` - Optional session UUID used to load compaction history
/// - ``usedTokens`` - Total tokens consumed in the context window
/// - ``contextWindowSize`` - Maximum context window capacity
/// - ``inputTokens`` - Total input tokens this turn
/// - ``outputTokens`` - Output tokens generated this turn
/// - ``cacheReadTokens`` - Tokens read from cache
/// - ``cacheCreateTokens`` - Tokens written to cache
/// - ``onForkSession`` - Optional action to fork the current session
/// - ``onDismiss`` - Action to dismiss this sheet
struct ContextWindowDetailSheet: View {
    /// Optional session ID used to load the compaction history for this session.
    var sessionId: UUID? = nil
    /// Total tokens consumed (input + output) in the context window.
    let usedTokens: Int
    /// Maximum capacity of the model's context window.
    let contextWindowSize: Int
    /// Total input tokens sent this turn (includes cached portions).
    let inputTokens: Int
    /// Output tokens generated by Claude this turn.
    let outputTokens: Int
    /// Tokens read from the prompt cache (prior conversation history).
    let cacheReadTokens: Int
    /// Tokens written to the prompt cache (new context being stored).
    let cacheCreateTokens: Int
    /// Optional closure to fork the current session. Shown as a button when percent ≥ 0.80.
    let onForkSession: (() -> Void)?
    /// Closure invoked to dismiss this sheet.
    let onDismiss: () -> Void

    @Environment(\.theme) private var theme: ThemeSnapshot
    /// Context snapshots loaded from SessionMemoryService for the compaction history section.
    @State private var snapshotHistory: [ContextSnapshot] = []

    // MARK: - Computed Properties

    /// Usage ratio clamped to [0, 1].
    private var percent: Double {
        guard contextWindowSize > 0 else { return 0 }
        return min(Double(usedTokens) / Double(contextWindowSize), 1.0)
    }

    /// Threshold-based color for the progress arc and warning banners.
    private var progressColor: Color {
        switch percent {
        case ..<0.80: return theme.accent
        case 0.80..<0.90: return theme.warning
        case 0.90..<0.95: return theme.warning
        default: return theme.error
        }
    }

    /// Fresh prompt content — excludes cached and tool-context tokens.
    private var newInputTokens: Int {
        max(0, inputTokens - cacheReadTokens - cacheCreateTokens)
    }

    // MARK: - Helpers

    private func formatTokens(_ count: Int) -> String {
        if count >= 1_000 {
            return String(format: "%.0fk", Double(count) / 1_000.0)
        }
        return "\(count)"
    }

    /// Percentage of `tokens` relative to total used tokens, formatted as "X%".
    private func sharePercent(_ tokens: Int) -> String {
        guard usedTokens > 0 else { return "0%" }
        return "\(Int(Double(tokens) / Double(usedTokens) * 100))%"
    }

    // MARK: - Body

    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(spacing: theme.spacingLG) {
                    progressCircle
                    warningBanner
                    breakdownSection
                    forkButtonSection
                    compactionHistorySection
                    footerSection
                }
                .padding(theme.spacingMD)
            }
            .scrollContentBackground(.hidden)
            .background(theme.bgPrimary)
            .navigationTitle("Context Window")
            #if os(iOS)
            .inlineNavigationBarTitle()
            #endif
            .toolbar {
                ToolbarItem(placement: .confirmationAction) {
                    Button("Done") { onDismiss() }
                        .foregroundColor(theme.accent)
                        .accessibilityLabel("Done viewing context window details")
                }
            }
        }
        .presentationDetents([.medium, .large])
        .presentationDragIndicator(.visible)
        .task(id: sessionId) {
            guard let sid = sessionId else { return }
            do {
                snapshotHistory = try await SessionMemoryService.shared.fetchSnapshots(forSession: sid)
            } catch {
                // Snapshot history is optional; silently ignore failures
            }
        }
    }

    // MARK: - Progress Circle

    /// Circular arc indicator showing overall context usage percentage.
    private var progressCircle: some View {
        VStack(spacing: theme.spacingSM) {
            ZStack {
                Circle()
                    .stroke(theme.bgTertiary, lineWidth: 14)
                    .frame(width: 128, height: 128)

                Circle()
                    .trim(from: 0, to: percent)
                    .stroke(
                        progressColor,
                        style: StrokeStyle(lineWidth: 14, lineCap: .round)
                    )
                    .frame(width: 128, height: 128)
                    .rotationEffect(.degrees(-90))
                    .animation(.easeInOut(duration: 0.5), value: percent)

                VStack(spacing: 2) {
                    Text("\(Int(percent * 100))%")
                        .font(.system(size: theme.fontTitle2, weight: .bold, design: theme.fontDesign))
                        .foregroundStyle(progressColor)
                        .contentTransition(.numericText())
                    Text("used")
                        .font(.system(size: theme.fontCaption, design: theme.fontDesign))
                        .foregroundStyle(theme.textTertiary)
                }
            }

            Text("\(formatTokens(usedTokens)) / \(formatTokens(contextWindowSize)) tokens")
                .font(.system(size: theme.fontBody, design: theme.fontDesign))
                .foregroundStyle(theme.textSecondary)
        }
        .frame(maxWidth: .infinity)
        .padding(theme.spacingMD)
        .glassCard()
    }

    // MARK: - Warning Banner

    /// Contextual warning banner shown at 80% and 95% thresholds.
    @ViewBuilder
    private var warningBanner: some View {
        if percent >= 0.95 {
            HStack(spacing: theme.spacingSM) {
                Image(systemName: "exclamationmark.triangle.fill")
                    .foregroundStyle(theme.error)
                Text("Context critically full. Fork session to avoid truncation.")
                    .font(.system(size: theme.fontBody, design: theme.fontDesign))
                    .foregroundStyle(theme.error)
                Spacer()
            }
            .padding(theme.spacingMD)
            .background(theme.error.opacity(0.12))
            .clipShape(RoundedRectangle(cornerRadius: theme.cornerRadius))
            .accessibilityLabel("Critical warning: context window is critically full")
        } else if percent >= 0.80 {
            HStack(spacing: theme.spacingSM) {
                Image(systemName: "exclamationmark.triangle.fill")
                    .foregroundStyle(theme.warning)
                Text("Approaching context limit. Consider forking the session.")
                    .font(.system(size: theme.fontBody, design: theme.fontDesign))
                    .foregroundStyle(theme.warning)
                Spacer()
            }
            .padding(theme.spacingMD)
            .background(theme.warning.opacity(0.12))
            .clipShape(RoundedRectangle(cornerRadius: theme.cornerRadius))
            .accessibilityLabel("Warning: approaching context window limit")
        }
    }

    // MARK: - Breakdown Section

    /// Per-category token breakdown displayed as a list of labeled rows.
    private var breakdownSection: some View {
        VStack(spacing: theme.spacingXS) {
            Text("Token Breakdown")
                .font(.system(size: theme.fontCaption, weight: .semibold, design: theme.fontDesign))
                .foregroundStyle(theme.textTertiary)
                .frame(maxWidth: .infinity, alignment: .leading)

            VStack(spacing: 0) {
                breakdownRow(
                    label: "Cached History",
                    description: "Prior conversation read from cache",
                    systemImage: "clock.arrow.circlepath",
                    tokens: cacheReadTokens,
                    color: theme.info
                )
                Divider()
                    .background(theme.divider)

                breakdownRow(
                    label: "New Input",
                    description: "Fresh prompt content this turn",
                    systemImage: "text.bubble",
                    tokens: newInputTokens,
                    color: theme.success
                )
                Divider()
                    .background(theme.divider)

                breakdownRow(
                    label: "Tool Context",
                    description: "New content being cached (files, tools)",
                    systemImage: "wrench.and.screwdriver",
                    tokens: cacheCreateTokens,
                    color: theme.entityMCP
                )
                Divider()
                    .background(theme.divider)

                breakdownRow(
                    label: "Output",
                    description: "Claude responses this turn",
                    systemImage: "arrow.turn.down.right",
                    tokens: outputTokens,
                    color: theme.warning
                )
            }
            .glassCard(padding: 0)
        }
    }

    /// A single row in the token breakdown list.
    private func breakdownRow(
        label: String,
        description: String,
        systemImage: String,
        tokens: Int,
        color: Color
    ) -> some View {
        HStack(spacing: theme.spacingSM) {
            Circle()
                .fill(color)
                .frame(width: 8, height: 8)

            Image(systemName: systemImage)
                .font(.system(size: theme.fontBody))
                .foregroundStyle(color)
                .frame(width: 20, alignment: .center)

            VStack(alignment: .leading, spacing: 2) {
                Text(label)
                    .font(.system(size: theme.fontBody, design: theme.fontDesign))
                    .foregroundStyle(theme.textPrimary)
                Text(description)
                    .font(.system(size: theme.fontCaption, design: theme.fontDesign))
                    .foregroundStyle(theme.textTertiary)
            }

            Spacer()

            VStack(alignment: .trailing, spacing: 2) {
                Text(formatTokens(tokens))
                    .font(
                        .system(size: theme.fontBody, weight: .medium, design: theme.fontDesign)
                        .monospacedDigit()
                    )
                    .foregroundStyle(theme.textPrimary)
                Text(sharePercent(tokens))
                    .font(.system(size: theme.fontCaption, design: theme.fontDesign))
                    .foregroundStyle(theme.textTertiary)
            }
        }
        .padding(theme.spacingMD)
        .accessibilityElement(children: .combine)
        .accessibilityLabel("\(label): \(formatTokens(tokens)) tokens, \(sharePercent(tokens)) of total")
    }

    // MARK: - Fork Button

    /// Prominent fork button shown when context usage exceeds 80% and a fork handler is provided.
    @ViewBuilder
    private var forkButtonSection: some View {
        if percent >= 0.80, let fork = onForkSession {
            Button(action: fork) {
                Label("Fork Session", systemImage: "arrow.branch")
                    .font(.system(size: theme.fontBody, weight: .semibold, design: theme.fontDesign))
                    .frame(maxWidth: .infinity)
                    .padding(theme.spacingMD)
                    .background(progressColor)
                    .foregroundStyle(theme.textOnAccent)
                    .clipShape(RoundedRectangle(cornerRadius: theme.cornerRadius))
            }
            .buttonStyle(.plain)
            .accessibilityLabel("Fork session to continue with a fresh context window")
        }
    }

    // MARK: - Compaction History

    /// List of past context snapshots taken before compaction events for this session.
    @ViewBuilder
    private var compactionHistorySection: some View {
        if !snapshotHistory.isEmpty {
            VStack(spacing: theme.spacingXS) {
                Text("Compaction History")
                    .font(.system(size: theme.fontCaption, weight: .semibold, design: theme.fontDesign))
                    .foregroundStyle(theme.textTertiary)
                    .frame(maxWidth: .infinity, alignment: .leading)

                VStack(spacing: 0) {
                    ForEach(Array(snapshotHistory.enumerated()), id: \.element.id) { index, snapshot in
                        snapshotHistoryRow(snapshot: snapshot)
                        if index < snapshotHistory.count - 1 {
                            Divider()
                                .background(theme.divider)
                        }
                    }
                }
                .glassCard(padding: 0)
            }
        }
    }

    /// A single row in the compaction history list showing timestamp and token count.
    private func snapshotHistoryRow(snapshot: ContextSnapshot) -> some View {
        HStack(spacing: theme.spacingSM) {
            Image(systemName: "scissors")
                .font(.system(size: theme.fontBody))
                .foregroundStyle(theme.warning)
                .frame(width: 20, alignment: .center)

            VStack(alignment: .leading, spacing: 2) {
                Text(snapshot.triggeredAt, style: .date)
                    .font(.system(size: theme.fontBody, design: theme.fontDesign))
                    .foregroundStyle(theme.textPrimary)
                Text(snapshot.triggeredAt, style: .time)
                    .font(.system(size: theme.fontCaption, design: theme.fontDesign))
                    .foregroundStyle(theme.textTertiary)
            }

            Spacer()

            VStack(alignment: .trailing, spacing: 2) {
                Text(formatTokens(snapshot.usedTokens))
                    .font(
                        .system(size: theme.fontBody, weight: .medium, design: theme.fontDesign)
                        .monospacedDigit()
                    )
                    .foregroundStyle(theme.textPrimary)
                if snapshot.contextWindowSize > 0 {
                    Text("\(Int(Double(snapshot.usedTokens) / Double(snapshot.contextWindowSize) * 100))%")
                        .font(.system(size: theme.fontCaption, design: theme.fontDesign))
                        .foregroundStyle(theme.textTertiary)
                }
            }
        }
        .padding(theme.spacingMD)
        .accessibilityElement(children: .combine)
        .accessibilityLabel("Snapshot from \(snapshot.triggeredAt.formatted()): \(formatTokens(snapshot.usedTokens)) tokens")
    }

    // MARK: - Footer

    /// Footer showing the model context limit and an optional truncation notice.
    private var footerSection: some View {
        VStack(spacing: theme.spacingXS) {
            HStack(spacing: theme.spacingXS) {
                Image(systemName: "cpu")
                    .font(.system(size: theme.fontCaption))
                    .foregroundStyle(theme.textTertiary)
                Text("Max context: \(formatTokens(contextWindowSize)) tokens")
                    .font(.system(size: theme.fontCaption, design: theme.fontDesign))
                    .foregroundStyle(theme.textTertiary)
                Spacer()
            }

            if cacheReadTokens > 0 && percent > 0.90 {
                HStack(spacing: theme.spacingXS) {
                    Image(systemName: "scissors")
                        .font(.system(size: theme.fontCaption))
                        .foregroundStyle(theme.warning)
                    Text("Conversation history may be truncated")
                        .font(.system(size: theme.fontCaption, design: theme.fontDesign))
                        .foregroundStyle(theme.warning)
                    Spacer()
                }
            }
        }
    }
}

// MARK: - Preview

#Preview("Normal usage") {
    ContextWindowDetailSheet(
        usedTokens: 50_000,
        contextWindowSize: 200_000,
        inputTokens: 40_000,
        outputTokens: 10_000,
        cacheReadTokens: 25_000,
        cacheCreateTokens: 8_000,
        onForkSession: nil,
        onDismiss: {}
    )
}

#Preview("Warning level (80–90%)") {
    ContextWindowDetailSheet(
        usedTokens: 168_000,
        contextWindowSize: 200_000,
        inputTokens: 140_000,
        outputTokens: 28_000,
        cacheReadTokens: 90_000,
        cacheCreateTokens: 20_000,
        onForkSession: { },
        onDismiss: {}
    )
}

#Preview("Critical level (≥ 95%)") {
    ContextWindowDetailSheet(
        usedTokens: 195_000,
        contextWindowSize: 200_000,
        inputTokens: 160_000,
        outputTokens: 35_000,
        cacheReadTokens: 120_000,
        cacheCreateTokens: 25_000,
        onForkSession: { },
        onDismiss: {}
    )
}
