import Foundation

/// Role of a message in a conversation.
public enum MessageRole: String, Codable, Sendable {
    /// Message sent by the user.
    case user
    /// Response generated by the assistant.
    case assistant
    /// System-level instruction or context.
    case system
}

/// Represents a message in a chat session (persisted in database).
public struct Message: Codable, Identifiable, Hashable, Sendable {
    /// Unique identifier for this message.
    public let id: UUID
    /// ID of the session this message belongs to.
    public let sessionId: UUID
    /// Role of the message sender (user, assistant, or system).
    public var role: MessageRole
    /// Plain text content of the message.
    public var content: String
    /// JSON-encoded tool invocation requests (if any).
    public var toolCalls: String?
    /// JSON-encoded tool execution results (if any).
    public var toolResults: String?
    /// Timestamp when the message was created.
    public let createdAt: Date
    /// Timestamp when the message was last modified.
    public var updatedAt: Date

    /// Creates a new message.
    /// - Parameters:
    ///   - id: Unique identifier (auto-generated if omitted).
    ///   - sessionId: ID of the parent session.
    ///   - role: Message sender role.
    ///   - content: Text content of the message.
    ///   - toolCalls: Optional JSON-encoded tool calls.
    ///   - toolResults: Optional JSON-encoded tool results.
    ///   - createdAt: Creation timestamp (defaults to now).
    ///   - updatedAt: Last update timestamp (defaults to now).
    public init(
        id: UUID = UUID(),
        sessionId: UUID,
        role: MessageRole,
        content: String,
        toolCalls: String? = nil,
        toolResults: String? = nil,
        createdAt: Date = Date(),
        updatedAt: Date = Date()
    ) {
        self.id = id
        self.sessionId = sessionId
        self.role = role
        self.content = content
        self.toolCalls = toolCalls
        self.toolResults = toolResults
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }
}
